### ISSUE TITLE
Set-Cookie header is being ignored

### ISSUE THREAD

**Issue by Kirlac** [jenius-apps/nightingale-rest-api-client#105]
I'm debugging some controller actions in an old MVC project which uses session cookies and it seems the [Set-Cookie header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) in the response is being ignored.

This isn't a major issue as it can be copied in manually as a workaround but a compliant HTTP client should probably be honoring this header and setting the cookie automatically.

**Comment by dpaulino** [comment]
Thanks for reporting this. I'll look into it as soon as possible

**Comment by Kirlac** [comment]
No rush - the workaround of copying it from the response header to the cookies is more than sufficient to get the job done.

Also I don't know if it makes any difference or not but this was for an asp.net MVC server running on localhost. Feel free to let me know if you need any more details or anything.

**Comment by dpaulino** [comment]
Found the issue. Thanks for spotting this. Fix will be available in the next update.
