### ISSUE TITLE
Feature request: Paste cURL to fill details

### ISSUE THREAD

**Issue by TheMisir** [jenius-apps/nightingale-rest-api-client#108]
It's not mandatory but might be a cool feature.

1. Copy curl command from some website
2. Open Nightingale

3.a. Check clipboard when window state changes (becomes active). If clipboard contains "curl .." then ask user if he/she wants to open a new tab with filled headers/body etc.
3.b. Or when user presses "Ctrl + V" key combination check if the text in clipboard is curl comment. Then open a new request tab with filled request details.

I would be happy to help if you need.

---

Some links I thought might be helpful:

* https://github.com/commandlineparser/commandline
* https://stackoverflow.com/questions/491595/best-way-to-parse-command-line-arguments-in-c
* https://fclp.github.io/fluent-command-line-parser/

**Comment by dpaulino** [comment]
Cool idea! I know postman lets you import from curl as well. Thanks for the feature request

**Comment by dpaulino** [comment]
There's been a lot on my plate for Nightingale, so to help speed things along, it'd be great if someone can help implement a curl-to-nigtingale converter. Once complete, I can quickly build a UX/UI for this functionality. Here's a stub that someone can build off of: https://github.com/jenius-apps/nightingale-core/blob/master/src/Nightingale.Converters/Curl/ICurlConverter.cs

**Comment by dpaulino** [comment]
The work involved for this task would be:
- create a `CurlConverter` class that implements `ICurlConverter`. 
- review the existing postman converter [here](https://github.com/jenius-apps/nightingale-core/tree/master/src/Nightingale.Converters/Postman) for an example

**Comment by TheMisir** [comment]
I found a MIT licensed [github repo](https://github.com/olsh/curl-to-csharp) which contains code for parsing curl command line arguments.

**Comment by dpaulino** [comment]
That's great. Perhaps we can convert the string to c# using that library, then convert from that lib to Nightingale.

**Comment by dpaulino** [comment]
@TheMisir were you interested in taking a crack at this? If so I can assign it to you. No worries if not though. Just want make it clear to potential contributors if the task is assigned to someone.

**Comment by TheMisir** [comment]
> @TheMisir were you interested in taking a crack at this? If so I can assign it to you. No worries if not though. Just want make it clear to potential contributors if the task is assigned to someone. 

I could work on it in 2-3 days, when I'm not busy.

**Comment by dpaulino** [comment]
@TheMisir looks like this curl to csharp library you found depends on `Span<T>` which is only supported in .NET Standard 2.1. UWP apps can only support .NET Standard 2.0, so this library can't be used without some modifications.

**Comment by dpaulino** [comment]
Scratch that, turns out you can import `System.Memory` and you can use `Spant<T>` in .NET Standard 2.0. 

I found some other issues though. The curl to csharp logic was not split out into a separate package, so you can't just nuget install it. I've done some preliminary work to split out the core logic into a separate project here: https://github.com/dpaulino/curl-to-csharp. However, there are some remaining compilation errors. See this screenshot.
![image](https://user-images.githubusercontent.com/7649589/96538865-74b99300-124e-11eb-8456-32de3e7dc5ed.png)

**Comment by dpaulino** [comment]
@TheMisir feel free to pick up that fork I created if you feel it might be useful

**Comment by TheMisir** [comment]
> @TheMisir looks like [this curl to csharp library](https://github.com/olsh/curl-to-csharp) you found depends on `Span<T>` which is only supported in .NET Standard 2.1. UWP apps can only support .NET Standard 2.0, so this library can't be used without some modifications.

I just mean we could use (copy) parsing part from that project. I'll look at that when I got free time.

**Comment by dpaulino** [comment]
coming soon: https://streamable.com/hg11o3

**Comment by dpaulino** [comment]
note: curl import support is currently rudimentary. If you see any data that you have isn't being imported, please open an issue in nightingale-core repo. And here's the current implementation of the curl converter: https://github.com/jenius-apps/nightingale-core/blob/master/src/Nightingale.Converters/Curl/CurlConverter.cs
