### ISSUE TITLE
App crashes when trying to import .ncf file via drag&drop

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#110]
- Freshly installed Nightingale v4.1.2.0
- Pause OneDrive manually (on my PC is was paused automatically because my laptop was in energy saving mode)
- Click "Import"
- Drag&drop .ncf file (not downloaded) from OneDrive (in Windows Explorer) into Nightingale
- Crash

Seems like Nightingale cannot handle the OneDrive placeholder file.

**Comment by dpaulino** [comment]
@tipa thanks for reporting this. Does selecting via file browser dialog work normally?

**Comment by tipa** [comment]
No, the "open" button is disabled when using the Windows dialog. It's not possible to work anyways as the file is online-only and the OneDrive app cannot download it as syncing is paused.

**Comment by dpaulino** [comment]
Ahh, I understand better now. I'll try to repro this soon to handle the OneDrive placeholder file.

**Comment by dpaulino** [comment]
Note to self
![image](https://user-images.githubusercontent.com/7649589/92848404-0ce67180-f39f-11ea-9c15-36067a784c44.png)

**Comment by dpaulino** [comment]
Now handling this error
![image](https://user-images.githubusercontent.com/7649589/93735141-cc51d980-fb90-11ea-9f5e-a17151183a9a.png)
