### ISSUE TITLE
Don't collapse Url field

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#112]
I am often working with very long URLs that span multiple lines in the URL field.
Unfortunately whenever I focus another textfield, that URL field collapses back to 1 line and I can't see the parameters any more. It would be better if it stayed expanded.

**Comment by dpaulino** [comment]
Adding an option to always keep URL text wrapped and expanded. Hope this will suffice! Coming in the next update
![image](https://user-images.githubusercontent.com/7649589/94356329-0d8b3300-0042-11eb-891b-93b7da99eae3.png)
