### ISSUE TITLE
Network requests cannot be intercepted by network traffic tools like Fiddler

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#116]
Sometimes I have the requirement to see the network requests that Nightingale sends out in Fiddler to exactly see what headers it sets or what response I get back. Unfortunately that doesnt work and the app shows: A security problem occurred.

Also when using the OAuth 2.0 flow while having Fiddler running, the auth window displays an error. This can be prevented by creating your own auth window instead of the AuthenticationBroker of the UWP SDK (which uses Internet Explorer internally and has plenty of problems) - send me a DM, I can send you the control which I am using for my apps.

**Comment by dpaulino** [comment]
Have configured fiddler to work with AppContainer-based apps? https://docs.telerik.com/fiddler/configure-fiddler/tasks/ConfigureFiddlerForWin8

**Comment by tipa** [comment]
Yes I did that and it's working perfectly when debugging web requests from my app - but not for Nightingale.
Does it work for you?

I checked the checkbox here:
![image](https://user-images.githubusercontent.com/2863198/94660250-b917da00-0305-11eb-85e5-e3206fd0e278.png)

**Comment by tipa** [comment]
Sure :)
