### ISSUE TITLE
OAuth 2.0 Authentication code flow stopped working

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#118]
I cannot get an access token using OAuth 2.0 any more with v4.1.3.0, I think it worked on the previous version. Because of #116 I also cannot see what exactly is wrong in the requests

![image](https://user-images.githubusercontent.com/2863198/94403526-e0d43a00-016d-11eb-8f72-ffada4c14e21.png)

**Comment by dpaulino** [comment]
Thanks for spotting this. Issue was a bug with how the callback url was being escaped. Fix incoming
