### ISSUE TITLE
Feature request: Add File Upload support on requests

### ISSUE THREAD

**Issue by lucimarckjsdias** [jenius-apps/nightingale-rest-api-client#12]
Hi!

I give a try to Nigthingale REST API Client (Preview) and I love how smooth, clean and beautiful the application have been evolved, one of the best UWP app sample, but I have a problem when I needed to create a request with file upload, so, sadly, I have to migrate to Insomnia App that offer the support for file uploads with Multipart Form. I would like to return to Nightingale if a similar feature are going to be implemented, until then I'll waiting for it.

**Comment by dpaulino** [comment]
Hi @lucimarckjsdias thanks for trying out Nightingale. There's an option to upload a binary file when you click on the `Body` pivot. Does that work for you or are you referring to a different feature when you say `file upload`?

![image](https://user-images.githubusercontent.com/7649589/66018750-272c8580-e495-11e9-938d-00d823cd7b7c.png)

**Comment by lucimarckjsdias** [comment]
Is different, look how is on Insomnia: 
![image](https://user-images.githubusercontent.com/30981574/66018821-a5e1ec80-e4ae-11e9-9485-7b2d1de6888d.png)

You can combine different type values in one request.

**Comment by dpaulino** [comment]
Ah yes, that's the multipart form. Thanks for the image! We are working on this ASAP because other people have requested the same feature. I will report back with updates on our progress. Thanks again for your feedback!

**Comment by dpaulino** [comment]
Quick update, we've completed this feature. It's now deployed to Nightingale preview members. We're going to monitor for bugs over the next few days. If all goes well, we'll deploy to the public sometime this week.

**Comment by dpaulino** [comment]
This feature is now available in Nightingale. Let me know if you encounter any issues! Closing ticket now
