### ISSUE TITLE
Insomnia importer does not transfer environment variables

### ISSUE THREAD

**Issue by sswires** [jenius-apps/nightingale-rest-api-client#123]
When importing a workspace export from Insomnia, it will import the individual requests with the correct verbs but it will not transfer the environment variables from the imported workspace. I have confirmed that the environment settings are in the exported JSON from Insomnia.

**Steps to Reproduce:**
1. Install Insomnia
2. Create a new workspace
3. Configure two environments that set the same variable
4. Use this variable as a part of a URL
5. Export Workspace from the Import/Export menu item
6. Attempt to import into Nightingale
7. Acknowledge that environment variables are not imported, and variables used in URLs are not reflected

**Expected Behaviour**

Environment variables and variables used in URLs, queries and HTTP headers are correctly reflected after import.

**Comment by dpaulino** [comment]
I just open sourced Nightingale's insomnia converter code. If anyone wants to help fix this bug, I'd be extremely grateful! Here is the insomnia code: https://github.com/jenius-apps/nightingale-core/tree/master/src/Nightingale.Converters/Insomnia

**Comment by jamesmcroft** [comment]
Came to see if this issue existed and it does! I might see if I can work this out 👍

**Comment by dpaulino** [comment]
Should be available in v4.4. now. If someone can check and confirm that it's working, please let me know!

**Comment by jamesmcroft** [comment]
Appears to be importing Insomnia workspaces correctly now but I'm seeing a different issue. Some environment variables don't seem to be replaced when making a request. 

I can dig into this a little further. Not sure if this is due to the import from Insomnia or something else.

**Comment by dpaulino** [comment]
If you have a repro steps can you make a new issue? I can investigate
