### ISSUE TITLE
Improve UI/UX after successful import. 

### ISSUE THREAD

**Issue by adrynalyne** [jenius-apps/nightingale-rest-api-client#127]
I have a Windows machine that I exported everything from Nightingale to a .ncf file. When I go to import it in Windows on another machine, I get a message that its ready for import but nothing actually happens when I close the window.

![image](https://user-images.githubusercontent.com/246382/95103795-ed1a4300-06e9-11eb-9366-49f612a52056.png)

![image](https://user-images.githubusercontent.com/246382/95103829-f86d6e80-06e9-11eb-8d2f-34a948fa6c80.png)

**Comment by dpaulino** [comment]
Click on the workspace drop down to see if your imported workspace was there
![image](https://user-images.githubusercontent.com/7649589/95104291-7fbae200-06ea-11eb-991b-113d898227da.png)

**Comment by dpaulino** [comment]
If it's there, then I'll file this as a UX/UI bug. Nightingale should do better at telling you where to find the import or automatically opening your imported workspace. Let me know if it's there

**Comment by adrynalyne** [comment]
> If it's there, then I'll file this as a UX/UI bug. Nightingale should do better at telling you where to find the import or automatically opening your imported workspace. Let me know if it's there

Sadly, it only has Base listed and nothing else.

**Comment by adrynalyne** [comment]
Wait!  Sorry, you are right, its there as you said it would be.

**Comment by dpaulino** [comment]
Phew, ok! I'll treat this as a UI/UX bug.

**Comment by dpaulino** [comment]
There's now a pop up whenever you successfully import a workspace 
![image](https://user-images.githubusercontent.com/7649589/96475088-73ee1600-11e8-11eb-8222-bc50295eb8b2.png)
