### ISSUE TITLE
Set Environment variable from response

### ISSUE THREAD

**Issue by gilmishal** [jenius-apps/nightingale-rest-api-client#128]
I think title is self explainatory, but basically I would love the ability to set an environment variable (such as token) based on a response to a request getting a token. (or even better, an ability to run an authentication request if no token is set, or if the response is 403/1, and then rerun the request).

**Comment by dpaulino** [comment]
If I understand you correctly, this might be what you are looking for https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/variablechaining.md

**Comment by gilmishal** [comment]
Yeah, that's it. Thanks. 
I would suggest improving the UX, making it easier to find for people who are unaware, but it's not really that important

**Comment by dpaulino** [comment]
Agreed on improving the UX to teach people where certain features live. I have plans to improve this across the app. I'll close this ticket for now though. Thanks for reaching out!
