### ISSUE TITLE
Request imported from postman v2.1 collection lose folder structure

### ISSUE THREAD

**Issue by roxk** [jenius-apps/nightingale-rest-api-client#133]
**Version**
Windows 10 2004
Nightingale 4.1.6.0

**Steps to reproduce the bug**
1. Import the following postman v2.1 collection:
```
{
	"info": {
		"_postman_id": "d3232d7e-a773-4953-8b80-0b5aa3fd79a5",
		"name": "Test Collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Test folder",
			"item": [
				{
					"name": "Test request",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "http://localhost:3001?param1=a&param2=b",
							"protocol": "http",
							"host": [
								"localhost"
							],
							"port": "3001",
							"query": [
								{
									"key": "param1",
									"value": "a"
								},
								{
									"key": "param2",
									"value": "b"
								}
							]
						}
					},
					"response": []
				}
			],
			"protocolProfileBehavior": {}
		}
	],
	"protocolProfileBehavior": {}
}
```
2. Observe "Test folder" is missing

**Expected behavior**
The folder is imported.

**Actual behavior**
The folder is not imported and Test request is at the root of the collection.

**Screenshot**
![image](https://user-images.githubusercontent.com/16918354/96879604-d37d4780-14ae-11eb-8ca5-90b9cb735591.png)

**Comment by dpaulino** [comment]
Now that your pr was merged, I'll assign this to me so I can add the updated package to the app

**Comment by dpaulino** [comment]
Thanks again for your contribution @roxk. The fix should now be available in the latest update
