### ISSUE TITLE
request works in the browser but not in app

### ISSUE THREAD

**Issue by cambo2015** [jenius-apps/nightingale-rest-api-client#135]
I don't think this is a bug per se but I installed a fresh windows 10 and installed the app, made a quick api. I user the app but no response, then I used the browser and I got a response. I love the app. Anyway any help would be great.

**Comment by dpaulino** [comment]
What's your url? Localhost? If so, have you tried this: https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

**Comment by cambo2015** [comment]
Yes it's localhost on port 8000. I'm testing this now.

**Comment by cambo2015** [comment]
I got it to work thanks to your help. Really appreciate it. Thanks 👍
