### ISSUE TITLE
Trailing question mark on all POST requests

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#139]
It appears that a question mark `?` is appended to all POST requests even though there are no parameters specified. This causes problems for some APIs, in my case this one: https://dev.fitbit.com/build/reference/web-api/oauth2/#retrieve-state-of-tokens
The endpoint returns
```
{
  "errors": [
    {
      "errorType": "not_found",
      "fieldName": "n/a",
      "message": "The API you are requesting could not be found."
    }
  ],
  "success": false
}
```
because of the trailing `?`

**Comment by dpaulino** [comment]
Thanks for reporting this. I'll look into it asap

**Comment by dpaulino** [comment]
@tipa fix should be available now. Can you try again?

**Comment by dpaulino** [comment]
It should be working now. Feel free to reopen if not!

**Comment by tipa** [comment]
Thanks for the quick fix
