### ISSUE TITLE
User agent header seems to be not sent

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/nightingale-rest-api-client#141]
According to reports

**Comment by dpaulino** [comment]
Can't seem to repro. See nightingale on the right supply a user-agent, and see aspnet core 5 on the left recognize that user-agent
![image](https://user-images.githubusercontent.com/7649589/99351394-577be280-2855-11eb-8528-c19e5b1f86b2.png)

**Comment by dpaulino** [comment]
Closing as no repro

**Comment by MahdiGhiasi** [comment]
I'm seeing the same behavior @jtippet explained.

Specifically, I was trying to repliacte [Google's FeedFetcher bot](https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers?visit_id=637946804161970914-3564226070&rd=1#feedfetcher) request which contains a semicolon that is not contained in parantheses. 

It is `FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)`, and Nightingale refuses to send this user agent.
