### ISSUE TITLE
Environment variables not working on URLs 

### ISSUE THREAD

**Issue by lozano-jorge** [jenius-apps/nightingale-rest-api-client#143]
Eg.

This works:
https://localhost:44354/connect/token

And this does not:
{{url}}/connect/token

**Comment by dpaulino** [comment]
I just tried this, and it worked for me. Can you show me a screen shot of your Log tab after you try to send the request? Here's a screenshot of my log tab, and you can see the url variable is working correctly
![image](https://user-images.githubusercontent.com/7649589/99309716-b8cc9300-280e-11eb-9453-3af0ee7d608b.png)

**Comment by lozano-jorge** [comment]
This is the variable:
![image](https://user-images.githubusercontent.com/1305049/99311581-ae1f0600-28c1-11eb-8dc9-818fb5fe82a8.png)

Log:
<img width="733" alt="Screenshot 2020-11-17 104221" src="https://user-images.githubusercontent.com/1305049/99311531-99db0900-28c1-11eb-9b33-aff39d0d8749.png">

I also tried without the last "/":
![image](https://user-images.githubusercontent.com/1305049/99311694-d575d300-28c1-11eb-882d-27e24d2515b8.png)

Log:
![image](https://user-images.githubusercontent.com/1305049/99311728-e58db280-28c1-11eb-9dc2-000be1c6ddd3.png)

**Comment by lozano-jorge** [comment]
Sorry never mind, it was the extra "/" sorry to waste your time.

**Comment by dpaulino** [comment]
No problem, feel free to open more issues if you find any!
