### ISSUE TITLE
[Feature request] Export as postman file

### ISSUE THREAD

**Issue by dpaulino** [jenius-apps/nightingale-rest-api-client#146]

**Comment by Ombrelin** [comment]
I am very interested in this feature

**Comment by dpaulino** [comment]
@Ombrelin any chance you'd be able to create a converter from nightingale to postman? Once a converter is created, I can easily enable it inside nightingale. Here are the converters for Nightingale (they're open source). You can fork this repo and create a class for nightingale to postman: https://github.com/jenius-apps/nightingale-core/tree/master/src/Nightingale.Converters

**Comment by Ombrelin** [comment]
Okay, thank you, I'll look into into it !

**Comment by andmig-ilty** [comment]
That would be a great feature. I just downloaded Nightingale and the first think I looked for was the export to Postman. We are heavy uses of "newman" to perform automated test based on postman collection scripts and test assertions.

**Comment by dpaulino** [comment]
@Ombrelin and @andmig-ilty: Is the export feature that you are imagining something like: right click on collection > export as postman?

**Comment by Ombrelin** [comment]
An option on the already existing Export menu would make more sens to me in term of UX, but if this is cumbersome, what you described would suit me as well

**Comment by dpaulino** [comment]
@Ombrelin yes I agree that spot makes more sense to me as well. However, I just realized that this menu would mean we're exporting the entire workspace from nightingale to postman. But right now, we only have code for converting collections. So I'm wondering if I have the correct models for a postman workspace 🤔

I'll have to investigate this a bit

**Comment by Ombrelin** [comment]
I'd say that starting with an Export to Postman in the collection contextual menu is a good idea, since being able to export a single collection would be welcome (not only for Postman !)

In the longer term, to export a workspace to Postman, can't you just for each collection of the nightingale workspace, use the export collection function ?

If this is not possible and more conversion code is needed, I'd be happy to contribute further to the core of you give me a spec.

**Comment by dpaulino** [comment]
> To export a workspace to Postman, can't you just for each collection of the nightingale workspace, use the export collection function

Yes I was thinking this too. Let me investigate what the schema for a postman workspace looks like. We may be able to make something by looping and converting each collection. 

> If this is not possible and more conversion code is needed, I'd be happy to contribute further to the core of you give me a spec.

Much appreciated. I'll let you know!

**Comment by dpaulino** [comment]
After some investigation, it appears that postman has a concept of a dump file which is equivalent to a workspace in Nightingale. Unfortunately, their dump file does not seem to have the same schema as their exported collection file... So I think we'll need 
- a new model in [Postman.NET](https://github.com/jenius-apps/Postman.NET/tree/master/src/Collections/Models) to represent their dump file
- new converter logic in PostmanConverter that converts to/from a Nightingale workspace

I think it makes more sense for the export menu to export a postman dump file, so I'll hold off in editing the export dialog menu. 

So for now, I will add a new feature to right click > export a collection into postman. 

@Ombrelin If you are still interested, would you be able to tackle the postman dump file converter task?

**Comment by Ombrelin** [comment]
>  I think it makes more sense for the export menu to export a postman dump file, so I'll hold off in editing the export dialog menu.
Totally agree.

> So for now, I will add a new feature to right click > export a collection into postman.
Great !

> If you are still interested, would you be able to tackle the postman dump file converter task?
Yes ! I'll sumbit a PR on both repos (Postman.NET & Nightingale Core) when my work will be ready for review.

**Comment by dpaulino** [comment]
Note: the task of supporting postman dump files is also related to this issue: https://github.com/jenius-apps/nightingale-rest-api-client/issues/33. When we add the support, I'll make sure to update this other ticket as well.

**Comment by dpaulino** [comment]
"right click > export as postman" is now available in v4.4. 

Regarding the postman dump file conversion, please post updates in #33!
