### ISSUE TITLE
Add hint to the tabs

### ISSUE THREAD

**Issue by calloncampbell** [jenius-apps/nightingale-rest-api-client#148]
Most often the name of the tab is longer than the tab itself. It would be nice if there was a hint element to display the full name of the request, and/or maybe also show the name of the tab above the URL field - similar to Postman.

**Comment by dpaulino** [comment]
Great feedback, thanks!

**Comment by dpaulino** [comment]
Adding a tooltip that opens the full request name if you hover over the tab 
![image](https://user-images.githubusercontent.com/7649589/106712382-b841ce00-65ad-11eb-9b06-6f524a66aff5.png)
