### ISSUE TITLE
Vancouver is spelled incorrectly

### ISSUE THREAD

**Issue by jtippet** [jenius-apps/nightingale-rest-api-client#170]
v4.3.8.0
About screen says "Vancouer", but probably meant "Vancouver"

![image](https://user-images.githubusercontent.com/10259764/111107344-ebb03a80-8513-11eb-8e58-bfd7c068d292.png)

**Comment by dpaulino** [comment]
This is a p0 bug. I will fix it with an emergency hotfix! (seriously) thanks for spotting!

**Comment by jtippet** [comment]
I have verified that the issue does not repro in v4.3.9.0.
