### ISSUE TITLE
No release notes for 4.3.9.0

### ISSUE THREAD

**Issue by paule96** [jenius-apps/nightingale-rest-api-client#171]
Hi,

I have today got the update `4.3.9.0` over the Microsoft Store. But I can't find release notes for it. Can you publish some release notes for it [here](https://github.com/jenius-apps/nightingale-rest-api-client/releases)?

**Comment by dpaulino** [comment]
Hello, I updated the changelog here https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/changelog.md. Hope that helps, thanks.
