### ISSUE TITLE
Feature request: Import from Postman

### ISSUE THREAD

**Issue by calloncampbell** [jenius-apps/nightingale-rest-api-client#18]
It would be nice if there was an import functionality to migrate from Postman.

**Comment by dpaulino** [comment]
@calloncampbell thanks for the feature request! I have this on the backlog near the top. Hoping to get to it soon. I'll keep you updated. Thanks again!

**Comment by dpaulino** [comment]
@calloncampbell heads up, this feature is now in store certification for public release. I have still marked the feature as `preview` in the app, though, as I'm sure there will be some edge cases I haven't accounted for. I'll update this thread once the update is available.

**Comment by dpaulino** [comment]
Nightingale 3.2.1 is now available with this feature.
