### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by milesje** [jenius-apps/nightingale-rest-api-client#182]
Importing from Insomnia (v4 JSON)

Unknown import error. Please create new issue on GitHub! Error message: Error reading string.
Unexpected token: StartObject. Path 'data.DEFAULT_HEADERS'.

**Comment by milesje** [comment]
So when I import a collection that doesn't have an DEFAULT_HEADERS it does import, but the environments do not import and what environment variables it does import it doesn't import correctly.
Example:  Here is a snippet of the Insomnia JSON export file where it defines an environment, but it is not imported.
```
{
      "_id": "env_5856389d6d2d4288acc5abf16400372d",
      "parentId": "env_a03c9e9754b3c6a4732d78d9a458cb43fd42105a",
      "modified": 1616677015216,
      "created": 1612987430751,
      "name": "Localhost",
      "data": {
        "host": "http://localhost:8080/CheckProcessor",
        "dataLib": "ICHK"
      },
      "dataPropertyOrder": { "&": ["host", "dataLib"] },
      "color": "#036821",
      "isPrivate": false,
      "metaSortKey": 1612987430751,
      "_type": "environment"
    }
```
Then when an environment variable is used in Insomnia it is stored as `{{ _.host }}`. I'm assuming that Insomnia is using lodoash which is why the variable when used starts with the understore "_.". This will need to be stripped out as well as having the white spaces removed (trimmed) between the curly braces and the variable name. So `{{ _.host }}` should be imported as `{{host}}`.  Removing the _. and trimming the white spaces.

**Comment by dpaulino** [comment]
I think this may have been resolved by https://github.com/jenius-apps/nightingale-rest-api-client/issues/123. 

We'll see how it goes in the next update which includes the fix

**Comment by dpaulino** [comment]
@milesje can you check the latest v4.4 if that solves your issue?

**Comment by dpaulino** [comment]
I believe this is solved by https://github.com/jenius-apps/nightingale-core/pull/11. Closing this ticket for now. Please re-open if you still find that it's not working. Thanks :)
