### ISSUE TITLE
Feature request: Word Wrap

### ISSUE THREAD

**Issue by coffeebank** [jenius-apps/nightingale-rest-api-client#20]
Hi, just wanted to start by saying, great app! Paid for premium and amazed at the quality and functionality of it all.

One recommendation I'd like to make is to add a word wrap option to the Body section when sending a POST so that all the text can be seen together without needing to scroll.

I tried to scroll with the middle button of my mouse but that hasn't worked either, so it's been sort of a pain to drag the horizontal scroll on the bottom left and right to see everything.

It would be great to see word wrap functionality. Thanks!

**Comment by dpaulino** [comment]
Thanks for the feature request! I'll investigate this as soon as possible.

**Comment by dpaulino** [comment]
@coffeebank sorry for the super long delay. Just finished the work for this. I'll be arriving with the next update. Thank you for your feedback!
