### ISSUE TITLE
Nightingale telemetry does not honor its privacy policy

### ISSUE THREAD

**Issue by jtippet** [jenius-apps/nightingale-rest-api-client#206]
The app's [privacy policy](https://1drv.ms/w/s!Ar4RhL72OhUDzpU99kslIFsO2p9UwQ) states:

> Analytics information:
>
> We may record diagnostic and usage information, such as the number of times you visited the settings page or the number of times you create a new request. This data is anonymous and is not traceable to an individual. This information is tracked to determine which features are being used so as to help guide what types of features to add or remove in the future. The data that you input into the app, such as URLs of requests, are not tracked

However, a fiddler capture shows that the app is indeed sending back the URL's hostname:

```
POST https://in.appcenter.ms/logs?api-version=1.0.0 HTTP/1.1
Install-ID: <<redacted>>

{
  "logs": [
    {
  "name": "Request sent",
  "properties": {
    "Hostname": "my-private-website.biz",      // <--- this
    "Method": "GET",
    "Body type": "None",
    "Auth type": "Basic"
  },
  "device": {
    "sdkName": "appcenter.uwp",
    "sdkVersion": "3.2.2",
    "appBuild": "4.4.0.0",
    "appNamespace": "43891JeniusApps.NightingaleRESTAPIClient"
  },
  "type": "event"
}
  ]
}
```

Please either update the privacy policy to indicate that a default installation of the the app does indeed phone home with private data that can potentially be used to uniquely identify a customer, or better yet, update the app to stop sending this information at all.

**Comment by dpaulino** [comment]
Fixed, thanks. Coming in v4.4.1

**Comment by jtippet** [comment]
Thanks for the quick turnaround. The store delivered v4.4.1 and I've confirmed that now no part of the URL is send in that telemetry event.
