### ISSUE TITLE
Feature request: Import swagger / OpenAPI definition

### ISSUE THREAD

**Issue by Suchiman** [jenius-apps/nightingale-rest-api-client#21]
Awesome design but it would be really handy if i could import my giant REST API from the auto-generated swagger definition!

**Comment by dpaulino** [comment]
Thanks for the feature suggestion! I've added this near the top of my backlog, and I will update this thread as soon as possible.

**Comment by dpaulino** [comment]
This feature is moving to the Preview program soon.

**Comment by dpaulino** [comment]
Coming in the next release. (update is in certification. ETA 3 days)

**Comment by iWantToKeepAnon** [comment]
I am using 4.3.7.0; where is the swagger import?  I tried saving the swagger JSON file and importing that but I get "Unsupported schema | unknown file type | serviceNameHere-swagger-odata.json".

**Comment by dpaulino** [comment]
@iWantToKeepAnon the swagger import currently only supports importing from yaml. I want to add json support soon but no promises on time. If you happen to have an opportunity to help, nightigale's converter code is open source: https://github.com/jenius-apps/nightingale-core/tree/master/src/Nightingale.Converters/Swagger

**Comment by Suchiman** [comment]
So far i've managed to get by by renaming the json file to yaml, since yaml is a superset of json.

**Comment by iWantToKeepAnon** [comment]
> nightingale's converter code is open source: https://github.com/jenius-apps/nightingale-core/tree/master/src/Nightingale.Converters/Swagger

I assume ".cs" is c-sharp?  It might be a good way to get my feet wet but I don't have any c-sharp experience or dev tools. : /  Thanks for the feedback and I might try the yaml trick to see how that works.

Thx.
