### ISSUE TITLE
Enhancement: Better manage environment support

### ISSUE THREAD

**Issue by calloncampbell** [jenius-apps/nightingale-rest-api-client#22]
The manage environments window could use some love in how it manages environments. 
- There doesn't seem to be a way to rename an environment.
- Would be nice to clone an environment.
- Environments can get an icon but there is no description of what the icon is and you can't change the icon. Why is there an icon?
- Longer environment names

**Comment by calloncampbell** [comment]
Should have a warning before deleting an environment

**Comment by mrjfalk** [comment]
Higher prio:
* Show which environment is active
* Allow setting which environment is the active one

Lower prio:
* Make dialog re-sizable
* Clicking outside dialog should close it

**Comment by dpaulino** [comment]
Thanks for the feedback. Some improvements to the environment UX is coming soon. It doesn't address most of the feedback, but I think it's an overall improvement. Let me know what you think.

![image](https://user-images.githubusercontent.com/7649589/80925553-8b723900-8d45-11ea-94ec-2fc4aed80100.png)

![image](https://user-images.githubusercontent.com/7649589/80925592-e572fe80-8d45-11ea-96e7-db5055e1900c.png)

**Comment by dpaulino** [comment]
Changes have been deployed. Let me know what you think and please create a new issue if there are more  problems! Thanks again for all your feedback

**Comment by dpaulino** [comment]
Also, for the items that I wasn't able to address, let me know if you'd like me to create new issues to track then
