### ISSUE TITLE
Timeout after 100 seconds 

### ISSUE THREAD

**Issue by paule96** [jenius-apps/nightingale-rest-api-client#225]
The app nightingale cancels any long going request after 100 seconds. This should be changed to infinite or maybe make this timeout configurable.

To test this you can make a simple dev webserver that just has a GET method that's make a thread.sleep für 105 seconds. This should just cancel the request in nightingale.

**Comment by Christoph-Wagner** [comment]
I have the same issue, API calls can take way longer than 100s

**Comment by udah1** [comment]
Any ETA for that one? it's making it less usable for debugging server code.

**Comment by dpaulino** [comment]
Added here: https://github.com/jenius-apps/nightingale-rest-api-client/commit/287492bb8ad97c88b3c705ac7dde1b1c114bd528.

It will be available in the next update
