### ISSUE TITLE
Can this app that installed by ms store can  connect to localhost  by default ?

### ISSUE THREAD

**Issue by John0King** [jenius-apps/nightingale-rest-api-client#233]
I download this app today,  and I find it don'st work with localhost by default ,   

if this is true , then can we add a new button on this app  main page (or setting page) that execute a cmd/powershell command for this issue ?

**Comment by dpaulino** [comment]
For most scenarios, the app will automatically execute the command behind-the-scenes. There are some scenarios, such as if you are not the administrator of your device, when this execution fails. If it's still not working, feel free to run the command manually https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md
