### ISSUE TITLE
[UI] Button is outside of viewing area

### ISSUE THREAD

**Issue by abmprottoy** [jenius-apps/nightingale-rest-api-client#246]
Hi there!
The "Delete All" button on the Manage Cookies flyout/Menu seems to be not responsive to Window size change and has a fixed position. As a result, when I was using Nightingale in a small window size, I didn't notice there was actually a Delete All button in that window until I Maximized the window again.

Here's a demo of the bug:
https://user-images.githubusercontent.com/115341293/213417160-91ec4b64-4b68-41f1-b8c6-f35562bb66e0.mp4

**Comment by dpaulino** [comment]
Fixed here: https://github.com/jenius-apps/nightingale-rest-api-client/commit/c20ba5585e46b46e05278f6b1c062316ebaa8ae4
