### ISSUE TITLE
Cannot send simple GET request to server on localhost:3000

### ISSUE THREAD

**Issue by AMDphreak** [jenius-apps/nightingale-rest-api-client#251]
Cannot connect to local server hosted on localhost:3000. Web browser could. Postman could. `curl` could, but not Nightingale.
Installed via Microsoft App Store

![image](https://user-images.githubusercontent.com/1058978/221737820-8ad49e34-ce2a-4401-8faf-f308ed6b07aa.png)

PS I like your GUI. Good work. Not too confusing, noisy, or oversimplified.

**Comment by dpaulino** [comment]
Try following this guide: https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

**Comment by AMDphreak** [comment]
> Try following this guide: https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

Thanks for the PSA. That is a shame. I suspected it might be AppStore policies affecting it. Microsoft needs to do something to accommodate.
