### ISSUE TITLE
Is This Application Still Supported?

### ISSUE THREAD

**Issue by CricutMike** [jenius-apps/nightingale-rest-api-client#264]
Hello, :-)
I just discovered this app, and I really like it. Smooth, simple, fast. It's great! However, I notice that the application has not been updated in the Windows Store since early 2022 (according to the `LastUpdateDateUtc` in [this JSON response](https://storeedgefd.dsx.mp.microsoft.com/v9.0/pages/pdp?productId=9N2T6F9F5ZDN&market=US&locale=en-US&appVersion=22205.1401.0.0&deviceFamily=Windows.Desktop) from windows store), and this makes me hesitate to use this app in my professional setting. Is development of this app still ongoing? I know it has already been mentioned why this app is not open source, but has that changed at all?

Thanks
-- Michael

**Comment by justummar** [comment]
I don't know if the app works in windows 11 or something I tried today and it couldn't even do a basic post request,  I confirmed my request was 100% correct because I tried in a .http file and in vscode with the rest extention, but this app kept failing.

**Comment by CricutMike** [comment]
@justummar For what its worth, I've been using it in Windows 11 successfully. 😊 However, I set up my requests directly in the UI, so you might consider trying that.

**Comment by dpaulino** [comment]
Yep still supported, but just haven't had much time to make some updates due to life events.  Will address some stuff soon!

**Comment by dpaulino** [comment]
FYI the LastUpdateDateUtc property doesn't represent the package being updated. It represents the product page's update date. For example if I edited the description of the app in the store, the LastUpdateDateUtc property would change. 

So just keep that in mind for the future. Just because that property is updated, it doesn't mean the app itself was updated.

**Comment by CricutMike** [comment]
Oh, that's actually very good information. Thank you, @dpaulino. And I completely understand life stuff keeping you busy. Really nice work on this project! If you are ever able to open it up, I'm sure there are plenty in the community that would love to support you! :-)
