### ISSUE TITLE
Auto assignement character "=" on query string is not compatible with some endpoints

### ISSUE THREAD

**Issue by damien-sorin** [jenius-apps/nightingale-rest-api-client#278]
I was trying to use nightingale to send some request to the web interface of a Marantz AVR

I wanted to send the following command:

`http://<ip>:<port>/goform/formiPhoneAppDirect.xml?SPPR%202`

but it did nothing on device side because nightingale actually send the following request

`http://<ip>:<port>/goform/formiPhoneAppDirect.xml?SPPR%202=`

which is ignored by the device as not supported request. Sending without the "=" via an other tool works well.

With Nightingale, I am not able to disable appending a "=" if no value is given for query parameter.

**Comment by dpaulino** [comment]
Fixed here: https://github.com/jenius-apps/nightingale-rest-api-client/commit/bd905a99eb0f65f04e7a3758c5e3db6d940b8a99
