### ISSUE TITLE
Clicking on "Import" crashes the app

### ISSUE THREAD

**Issue by lordkyuusei** [jenius-apps/nightingale-rest-api-client#281]
### Issue
When clicking on the Import button, the app crashes. I've been given a corporate PC for work and my team uses Postman Cloud, but due to licensing stuff I can't use it yet. So I've thought about using Nightingale, downloaded it, hit 'import' and that's how I find it out :(

### System configuration
- Windows 11 Pro 23H2 build 22631.3296
- Nightingale v4.4.3

### Video / Reproduce steps

https://github.com/jenius-apps/nightingale-rest-api-client/assets/18118930/405956dc-7f16-46f7-9244-4fe6168a2904

Thanks for any help you can provide! :)

**Comment by dpaulino** [comment]
That's an insane crash wow. Nice find. I cannot reproduce this yet on v4.5. Any chance you can reproduce on the latest version? You can get the latest from the microsot store

**Comment by lordkyuusei** [comment]
It's working fine on 4.5.0! :) Not sure what happened in the previous version but that one solves it so good job fixing bugs you're not aware of LOL

**Comment by dpaulino** [comment]
Great 😂
