### ISSUE TITLE
Light theme bug: text selection in Body: form-data tab

### ISSUE THREAD

**Issue by kryvyifedir** [jenius-apps/nightingale-rest-api-client#29]
There is a bug with text selection on some tabs in the light theme. 
"body -> form-data -> value" selection issue screenshot:
![image](https://user-images.githubusercontent.com/23722132/70520161-ca5ce380-1b45-11ea-8ffc-1b9672702445.png)

For your convenience I have double checked all other tabs and selections as well and it seems this is the only issue 
Here is all tabs that I have tested:
Queries: [ 
    Key + ; 
    Value + 
]
Auth: [ 
    Basic + ; 
    Oauth 1.0 + ; 
    Oauth 2.0 ; 
    Bearer +; Digest +
]
Headers: [ 
    Key + ; 
    Value + 
]
Body: [ 
    Json + ; 
    XML + ; 
    x-www-form: [ 
        Key + ; 
        Value +
    ]  ; 
    form-data: [
        ContentType + ; 
        Key+ ; 
        **Value -** 
    ]
Chain: [ 
    Variable to update + ; 
    Response property +
]

**Comment by dpaulino** [comment]
Thanks for the bug report! Will look into it soon

**Comment by dpaulino** [comment]
issue has been addressed and it'll be available in a future release

**Comment by dpaulino** [comment]
This fix is included in the next release coming soon.
