### ISSUE TITLE
Bug: Creating a new request item doesn't update list selection on left

### ISSUE THREAD

**Issue by hawkerm** [jenius-apps/nightingale-rest-api-client#32]
If I have a current request selected, and then I create a new one (or duplicate an existing one), the form updates to show the blank/duplicate info, but the list on the left doesn't select the new item.  This makes it confusing to see that it's currently on the new request.  It also makes it hard to switch back to the one that's still selected, as you have to click twice (off of it and back again).

v3.2.1.0

**Comment by dpaulino** [comment]
Thanks for reporting this. I think this is blocked by the WinUI treeview's limited selection APIs. I'll double though

**Comment by dpaulino** [comment]
I've implemented this, but you'd occasionally get this crash: https://github.com/microsoft/microsoft-ui-xaml/issues/2303

**Comment by dpaulino** [comment]
After further testing, this crash is unfortunately way too frequent. I will be not be including this feature into Nightingale until the crash has been addressed.

**Comment by dpaulino** [comment]
These crashes seem related to this issue in the winui repo: https://github.com/microsoft/microsoft-ui-xaml/issues/2465

**Comment by dpaulino** [comment]
Marking this as closed and obsolete because Nightingale 4 changed the UX when creating a request.
