### ISSUE TITLE
Feature request: Import from Insomnia

### ISSUE THREAD

**Issue by electronic-dk** [jenius-apps/nightingale-rest-api-client#36]
It would be great to have the ability to import data from Insomnia (a popular REST-client similar to Postman) https://insomnia.rest/
Here's the description of the export format: https://support.insomnia.rest/article/52-importing-and-exporting-data

Thank you.

**Comment by dpaulino** [comment]
Thanks for the feature request! This has been one of the most requested features, so I hope to start working on this soon
