### ISSUE TITLE
Bug: variables doesn't seem to work in Auth tab.

### ISSUE THREAD

**Issue by lordkyuusei** [jenius-apps/nightingale-rest-api-client#38]
Hi Daniel!

I would like to submit a bug i'm facing right now. I have an environment with variables. Those variables, when templated like {{this}} work well when it's in the URL.

![image](https://user-images.githubusercontent.com/18118930/72805292-d2369a00-3c52-11ea-96c3-a32178756944.png)
_Screenshot of Nightingale with correct inputs and correct output._

{{frontname}}:{{apiMgrPort}} is correctly translated and my request works.

However, when I replace my Auth credentials:
![image](https://user-images.githubusercontent.com/18118930/72805375-001bde80-3c53-11ea-8907-b3ffe4f83081.png)
_Screenshot of Nightingale with correct inputs and incorrect output._

Well, it doesn't work anymore.
My base environment does have the right values:
![image](https://user-images.githubusercontent.com/18118930/72805468-3bb6a880-3c53-11ea-9a21-f90c8838767a.png)
_Screenshot of my Nightingale base environment variables._

Did I do something wrong, or maybe is it not yet supported?

_EDIT: I'm using Nightingale 3.2.4.0._

Thanks!

**Comment by dpaulino** [comment]
Thanks for creating an issue! Nightingale does not yet support using variables in the password, but it should be working for the username. So you likely found a bug!

Let me take a look at this, and I may just add support for password variables while I'm investigating the username. Thanks again!
