### ISSUE TITLE
Request Headers doesn't allow to set a charset

### ISSUE THREAD

**Issue by kryvyifedir** [jenius-apps/nightingale-rest-api-client#40]
Hi Nightingale,

I am currently working on an integration with Pocket API, and it seems that I have found a peculiar issue
Here is an authorization API
https://getpocket.com/developer/docs/authentication

It states that basically 2 Headers have to be included in first POST request
Content-Type: application/x-www-form-urlencoded; charset=UTF8
X-Accept: application/x-www-form-urlencoded

Here is a setup in Nightingale
![image](https://user-images.githubusercontent.com/23722132/72898701-4180bc80-3d2d-11ea-8343-14d39316bf34.png)

And here is a body:
![image](https://user-images.githubusercontent.com/23722132/72898910-a9370780-3d2d-11ea-9033-38837f41cf7e.png)

I am trying to send request and getting 406 error instead.
When returning to the Headers tab, I can see that Content-Type is missing 'charset'
![image](https://user-images.githubusercontent.com/23722132/72898879-97edfb00-3d2d-11ea-9787-709717472584.png)

The thing is that I have done this previously in postman, and I have a .net UWP app that basically does the same thing and they both can send this request just fine, so I am assuming this is somehow related to Headers setup.

I haven't found another place where I would be able to provide a charset manually so this proves to be quite an issue

**Comment by dpaulino** [comment]
Thanks for spotting this bug. I have now fixed the issue. This fix will be available in the next update!
