### ISSUE TITLE
Search dialog is not getting focus on ctrl+f

### ISSUE THREAD

**Issue by MikeyMCZ** [jenius-apps/nightingale-rest-api-client#42]
Hi Daniel,

I would like to report a bug. When I try to search in the response json I use ctrl+f shortcut on my keyboard. The Search dialog is opened however it doesn't have focus. So when I start typing I usually end up editing the response body.

I'm using 3.2.4.0

Thank you!

**Comment by dpaulino** [comment]
Cause of issue was that the search bar UI wasn't fully rendered yet before the `Focus` command was executed. I've fixed this now, and it will be available in the next release.
