### ISSUE TITLE
Request on localhost not working 

### ISSUE THREAD

**Issue by Ombrelin** [jenius-apps/nightingale-rest-api-client#44]
Trying do perform a request on a localhost spring boot server with nightingale. The request times out, however, with postman the exact same request works as expected.

**Comment by dpaulino** [comment]
Hello 👋🏽 Thanks for creating an issue! Can you try this troubleshoot step? https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

Let me know if that works or not.

**Comment by Ombrelin** [comment]
It worked thank you
