### ISSUE TITLE
Feature request: Informing about the workaround when trying to access localhost

### ISSUE THREAD

**Issue by rico-et22** [jenius-apps/nightingale-rest-api-client#45]
It would be nice if Nightingale informed the user about the necessary workaround command when trying to access a resource in localhost.
It can be done for example by detecting "localhost" in the address bar and then triggering the warning.

**Comment by dpaulino** [comment]
Thanks for the feedback! Just double checking, are you referring to the SSL workaround of the checknetisolation workaround? Or perhaps both?

**Comment by rico-et22** [comment]
I'm referring to checknetisolation.

**Comment by dpaulino** [comment]
Gotcha! So, Nightingale actually performs this workaround automatically for you when it's first launched. The only known occasion when this automatic execution fails is when your Windows User account is not an administrator. 

So it sounds like this auto execution didn't work for you. Any chance you're not an administrator?

**Comment by rico-et22** [comment]
🤔... Yes I am in the administrator group (standard Microsoft account created on first time configuration, UAC enabled). BTW I'm running an Insider build

**Comment by dpaulino** [comment]
Interesting. If you're up for doing a bit of testing, I'd be curious to see what happens when you uninstall and reinstall Nightingale and then try to make a call to localhost. (Make sure to turn off SSL verification after reinstalling so that doesn't interfere with the test result). 

I'll do some of my own testing as well

**Comment by sakisds** [comment]
I've had the same issue on a fresh installation. I found the workaround on this repo that fixed the problem but reinstalling didn't seem to do anything. My account is an administration, UAC enabled.

Any info I can provide that could prove helpful?

**Comment by dpaulino** [comment]
I've been getting reports left and right about this. I'm starting to wonder if Microsoft has updated Windows to prevent Nightingale from automatically getting localhost access.

Can you reply with your Windows version and build? You can search for winver in your Taskbar to get this info

**Comment by sakisds** [comment]
I am on Version 1909, Build 18363.720.

**Comment by dpaulino** [comment]
@sakisds thanks. I have a feeling Microsoft made changes in 1909 that has affected Nightingale. I will work on adding a help message about localhost into Nightingale

**Comment by dpaulino** [comment]
I have added a clickable message at nightingale's bottom bar when the user send a requests to localhost. Clicking on the message brings up the localhost doc. The update is now compiling and it will be deployed to preview members in a few hours. It should become available to the public sometime this week.

**Comment by dpaulino** [comment]
3.2.9 now available. It shows a banner at the bottom status whenever you attempt to connecto to localhost.
![image](https://user-images.githubusercontent.com/7649589/77607301-19e9d400-6ed7-11ea-97a8-b0d24b352210.png)

**Comment by dpaulino** [comment]
Thanks @sakisds and @rico-et22!
