### ISSUE TITLE
Connection Issues while hitting APIs

### ISSUE THREAD

**Issue by prkhandelwal** [jenius-apps/nightingale-rest-api-client#46]
Receiving the following error while hitting localhost APIs.

```
An error occurred while sending the request. The text associated with this error code could not be found.

A connection with the server could not be established
```

SSL validation is turned off!

**Comment by dpaulino** [comment]
Hello 👋🏽 Thanks for creating an issue! Can you try this troubleshoot step? https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

Let me know if that works or not.

**Comment by prkhandelwal** [comment]
Thanks @dpaulino , it now works! 🙌
