### ISSUE TITLE
Inherit authentication from collection

### ISSUE THREAD

**Issue by secana** [jenius-apps/nightingale-rest-api-client#47]
One of the features from Postman which I miss a lot in Nightingale is the possibility to inherit authentication options from a collection.

For example: If I have a collection with REST request for my ElasticSearch cluster, I need to set the authentication in every request in the collection. 

What I want: Set the authentication information once in on the collection level and all requests in the collection are inheriting the authentication information with a simple "inherit from collection" flag. With that I need to only provide the information once.

**Comment by dpaulino** [comment]
Thanks for the feature request! Agreed that this would be super useful. I'll investigate how much work is needed to implement this and I'll post updates soon.

**Comment by dpaulino** [comment]
I'm pleased to report that this is now in alpha testing. If all goes well, it will be publicly available sometime this week.

**Comment by dpaulino** [comment]
Accidentally closed the issue using the GitHub app... Reopening

**Comment by secana** [comment]
Great to hear. Will try at soon as it is available in the store. Thanks for implementing the feature!

**Comment by dpaulino** [comment]
Nightingale 3.3.0 now available with this new feature. Please try it out and feel free to create a new issue if you find any problems!
