### ISSUE TITLE
Feature request: add changelog

### ISSUE THREAD

**Issue by hoilc** [jenius-apps/nightingale-rest-api-client#5]
Hi,

I'm interested in new features of Nightingale. However Microsoft Store doesn't provide release information.

It could be nice to add 'Changelog' tab to 'Setting' panel.

Also a 'What's New' panel could pop up when new version of Nightingale launch for the first time.

Regards

**Comment by dpaulino** [comment]
Thanks for creating an issue for this. The Microsoft Store seems to have a bug where the "what's new" section disappears for some apps. You can see on the webpage that we added an extensive change log, but I agree that it'd be even better to have this info in the app. It'll be added as soon as possible. Thanks again.
![image](https://user-images.githubusercontent.com/7649589/55492716-8a278780-55ec-11e9-8096-3786a8277258.png)

**Comment by dpaulino** [comment]
Work completed. This will be included in an upcoming update.
