### ISSUE TITLE
No 'Implicit' grant type in OAuth 2.0

### ISSUE THREAD

**Issue by prkhandelwal** [jenius-apps/nightingale-rest-api-client#50]
![image](https://user-images.githubusercontent.com/12965931/75349075-0b090500-58ca-11ea-9c26-53234a434247.png)

**Comment by dpaulino** [comment]
@prkhandelwal Out of curiosity, are you attempting to access a service that uses implicit flow? Or are you developing something yourself where you are implementing implicit flow?

**Comment by prkhandelwal** [comment]
Hey @dpaulino , I was just learning about OAuth2.0 and experimenting with different workflows in IdentityServer4.
