### ISSUE TITLE
In the Test definition, add concept of Pass/Fail, not just displaying status and message.

### ISSUE THREAD

**Issue by sharpninja** [jenius-apps/nightingale-rest-api-client#53]
Current, if you create a test for an error condition, then success of that test actually says Error on the screen.  Unless the viewer is expecting that to be a successful test, then it would be a false indicator.

**Comment by dpaulino** [comment]
Tests have been temporarily removed from Nightingale. I hope to improve the design on the future when it's reintroduced. Closing this ticket since this pertains only to the old design that SAS removed.
