### ISSUE TITLE
Authentication inheritance not working

### ISSUE THREAD

**Issue by secana** [jenius-apps/nightingale-rest-api-client#55]
I just tried out the new authentication inheritance but it does not work.

Version 3.3.0.0

What I've tried:

1. Add credentials to collection item (Basic Auth)
2. Remove credentials from child items
3. Check "Parent" tab: "This item will inherit its parent's authentication"
4. Send the request: Results in 401 Unauthorized

With the same credentials directly on the child item it works fine.

**Comment by dpaulino** [comment]
I'll take a look, thanks!

**Comment by dpaulino** [comment]
Just double checking, how are you sending the request? Via the "Execute all" button in the collection page or via the "Send" button in the request's page?

**Comment by dpaulino** [comment]
I think I've isolated the bug. Can you try this:
- open nightingale
- create new collection and add basic auth details
- create new request inside that collection and use parent auth
- send request (auth should not work)
- then save your workspace
- send request again (auth should work)

Can you let me know if the auth works after you save the workspace? I think that's the bug. The inheritance isn't working until after you save the workspace. Please let me know if you can confirm this. I'll be working on fixing it as soon as possible.

**Comment by dpaulino** [comment]
New 3.3.1 update rolling out to alpha testers with this fix just in case you confirm that the previous workaround does work for you. If it does not work, let me know and I'll investigate further.

**Comment by dpaulino** [comment]
3.3.1 now available. Please try it and let me know if you're still encountering an issue!

**Comment by secana** [comment]
Hi I'll try it out as soon as the new version is available in the store. I checked just now, and the most up to date is still 3.3.0.0

**Comment by dpaulino** [comment]
Woops, I spoke too soon earlier. Looks like it got deployed to beta testers and the production release is still being certified by the store. I'll report back once it's deployed

**Comment by dpaulino** [comment]
The update should be available now.

**Comment by secana** [comment]
Hi @dpaulino just tried out the new version and it works now. Thanks for the very fast fix!
