### ISSUE TITLE
Please Add Content Encoding Information to Response Headers

### ISSUE THREAD

**Issue by wjvii** [jenius-apps/nightingale-rest-api-client#56]
In particular I am working to optimize the apps use of compression so I would like to see when content is returned using some form of compression similar to the following:

Content-Encoding: br

Thank you.

**Comment by dpaulino** [comment]
I will look into this soon, thanks.

**Comment by wjvii** [comment]
Thank you so much. It will help if knowing that things are properly configured.

BTW, I would be curious to know how you end up implementing this to see if there is a better way. I expected this in a Content-Encoding Header but I did not see that when using the HttpClient. When doing some tests in LINQPad I found that I could get the response.Content.GetType() from the HttpClient and if it was being decompressed the type would be a handler and it would be System.Net.Http.DecompressionHandler+GZipDecompressedContent or System.Net.Http.DecompressionHandler+BrotliDecompressedContent depending on what the server could handle.

**Comment by dpaulino** [comment]
@wjvii Looks like Nightingale can already return the `Content-Encoding` header like the picture below. Do you not see this header in your usage?

![image](https://user-images.githubusercontent.com/7649589/80321856-86593b00-87d5-11ea-8a6b-7b1635ef3d37.png)

**Comment by wjvii** [comment]
You are correct and my bad for not realizing this myself. I was not thinking about the fact that compression, even when supported by the server, is not automatically used by the client without the proper Accept-Encoding header. Thank you for reminding me.
