### ISSUE TITLE
Importing from Postman throws error on [] 

### ISSUE THREAD

**Issue by merlinfrombelgium** [jenius-apps/nightingale-rest-api-client#57]
Importing a Postman json export throws the following error:

![image](https://user-images.githubusercontent.com/26247323/80197519-0be6ba80-861f-11ea-84da-97c3f1a99563.png)

This is the culprit part of the json file:
```
"body": {
	"mode": "formdata",
	"formdata": [
		{
			"key": "receipt",
			"description": "A receipt file to attach to the expense. If including a receipt, you must submit a multipart/form-data request.",
			"type": "file",
			"src": [],
			"disabled": true
		}
	]
},	

```
Changing `"src": []` to `"src": ""` fixes it and import is successful.

![image](https://user-images.githubusercontent.com/26247323/80198410-51f04e00-8620-11ea-9340-e0257625cd8f.png)

**Comment by dpaulino** [comment]
Interesting, it looks like postman exports the formdata `src` property as a string if there's only one path. If there are 0 or >1 paths, postman exports `srs` as an array. This makes deserialization not straightforward. I'm going to investigate a workaround for this.

**Comment by dpaulino** [comment]
Fixed it with this commit: https://github.com/jenius-apps/Postman.NET/commit/dfe57f8524fe5d76b5929fac26c974429bbaecee

The fix will be deployed to Nightingale soon.

**Comment by dpaulino** [comment]
Update is now rolling out in the store. Thanks very much for your feedback!
