### ISSUE TITLE
Bug: Multiple imported workspaces from same file being deleted

### ISSUE THREAD

**Issue by pinholucas** [jenius-apps/nightingale-rest-api-client#61]
When the user import the same .ncf multiple times, the app only keeps the last one imported, deleting all the others (when the user closes the app).

**Comment by dpaulino** [comment]
Going to investigate asap, thanks for reporting. Sorry for the trouble

**Comment by dpaulino** [comment]
Fixed. Coming soon.

**Comment by dpaulino** [comment]
Update now available
