### ISSUE TITLE
Display response as image

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#62]
Would be cool if I could see the response body as image view. Fiddler offers that for example. This features would be especially helpful when playing with image queries that dont have a ".jpg" file extension, eg. `https://public.db.files.1drv.com/verylongid?width=800&height=533&cropmode=none`

![image](https://user-images.githubusercontent.com/2863198/81534125-ca1c7a80-9367-11ea-8b5f-bf505bccbebf.png)

Ideally I could even drag-drop the image from the app to my desktop

**Comment by dpaulino** [comment]
> helpful when playing with image queries that dont have a ".jpg" file extension

@tipa when you say this, are you saying that the URL query does not have an image extension? or are you saying that the content type of the URL response is not `image/xxxx`? Or both?

**Comment by dpaulino** [comment]
In other words, I'm wondering if you imagine a situation where you want to display an image even when the response's content type is not `image/xxxx`

**Comment by tipa** [comment]
Right, the URL doesnt end with ".jpg".
In the specific case that I was missing this feature the header of the response did have the header set to "image/jpg" but I think the option could be visible regardless of the header
