### ISSUE TITLE
Add button/setting to decompress GZIP-compressed data

### ISSUE THREAD

**Issue by tipa** [jenius-apps/nightingale-rest-api-client#67]
When specifying the header "Accept-Encoding: gzip, deflate", servers often respond with the response body compressed with GZIP  (or another accepted encoding specified in the request).
Fiddler offers a button to decompress the data:
![image](https://user-images.githubusercontent.com/2863198/82155263-e2166180-9873-11ea-9d4e-f837a8acc54e.png)

![image](https://user-images.githubusercontent.com/2863198/82155268-e478bb80-9873-11ea-9099-88ff15d3e615.png)
Nightingale currently only shows the compressed data.
Additionally, it could be interesting to know the size of both the the compressed and uncompressed data (e.g. to find out how much bandwidth was saved by using GZIP)

**Comment by sebbouez** [comment]
Hello @dpaulino 
Is this feature on your roadmap?
It would be perfect to stop using Fiddler aside.

Thank you!

**Comment by dpaulino** [comment]
@sebbouez yes I'll be working on this! Can't make promises on ETA though, since I'm dealing with life events (good things!) at the moment.
