### ISSUE TITLE
Alternate download not on Microsoft Store

### ISSUE THREAD

**Issue by treisska** [jenius-apps/nightingale-rest-api-client#68]
Is there a way to download Nightingale from another source?
I don't have access to Microsoft Store on my work computer and I guess people stuck on old versions of Windows would be happy too.

**Comment by dpaulino** [comment]
Hi @treisska thanks for the question. At this time there is no alternate download outside the Microsoft Store. The reason is because Nightingale makes use of the store's payment SDK at the moment. 

I have plans to address this, but I can't give a timeline right now unfortunately.

**Comment by treisska** [comment]
Hello,

Thank you for your quick answer!
That's a shame, I guess I'm stuck with Postman for now.
