### ISSUE TITLE
Publish nightingale in winget

### ISSUE THREAD

**Issue by electronic-dk** [jenius-apps/nightingale-rest-api-client#69]
Microsoft has announced a package manager for windows: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

It would be cool to have Nightingale published in this package management solution.

The packages should be submitted here
https://github.com/microsoft/winget-pkgs

**Comment by dpaulino** [comment]
I'll investigate this soon. Looks like one option is that winget adds the ability to install store apps. As I do more research, please give a thumbs up for this issue: https://github.com/microsoft/winget-cli/issues/117

**Comment by dpaulino** [comment]
Looks like the winget team is including Microsoft Store support in their v0.2 milestone due June 30th, 2020. When this lands, I will make sure to add Nightingale

**Comment by denelon** [comment]
The Store support feature https://github.com/microsoft/winget-cli/issues/117 will likely be released initially behind a feature toggle. We will likely only support "Free" apps rated "E" for Everyone. The good news is "The Nightingale REST API Client" meets these initial limitations.

**Comment by denelon** [comment]
`winget search nightingale` will display the Microsoft Store version of Nightingale (if you have the experimental feature enabled).

`winget install "Nightingale REST Client"` will install it by name
`winget install 43891JeniusApps.NightingaleRESTAPIClient` will install it by ID

**Comment by dpaulino** [comment]
Just tested out the experimental feature and it works great! Thanks @denelon!! I also created this doc for users who want to install Nightingale via winget: https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/winget.md

**Comment by dpaulino** [comment]
@electronic-dk thoughts on keep this open until this feature leaves the experiment phase of winget?

**Comment by electronic-dk** [comment]
@dpaulino I'm cool with that. Thanks for the update, I'll try to install nightingale via winget soon.
