### ISSUE TITLE
Feature request: import from curl

### ISSUE THREAD

**Issue by sylveon** [jenius-apps/nightingale-rest-api-client#70]
Postman has a very useful feature where we can import a request by pasting a curl command:

![image](https://user-images.githubusercontent.com/6440374/82763071-d32f3200-9dd2-11ea-90dc-3d41bec995c7.png)

I would like to see this in Nightingale, as it makes importing from many online API docs or samples trivially easy.

We can copy a curl command from the web browser dev tools as well, and then paste it in Postman to reproduce the exact API call that a webpage did, which is useful for debugging:

![image](https://user-images.githubusercontent.com/6440374/82763101-20130880-9dd3-11ea-9915-7f6342ac4ad3.png)

**Comment by dpaulino** [comment]
Some work for this will overlap with https://github.com/jenius-apps/nightingale-rest-api-client/issues/108. I'll keep this open for now, but once any curl import feature is in nightingale, I'll close this.

**Comment by dpaulino** [comment]
Examples of curl statements: https://api.cloudflare.com/#getting-started-responses

**Comment by dpaulino** [comment]
coming soon
![image](https://user-images.githubusercontent.com/7649589/99503756-718bf280-2933-11eb-9816-dc7822f72049.png)
