### ISSUE TITLE
Query parameters with the same key get merged into one parameter

### ISSUE THREAD

**Issue by yoshiask** [jenius-apps/nightingale-rest-api-client#72]
When I GET the following URL, it works fine in a browser, but in Nightingale the exact same URL produces an error from the API.
https://graphhopper.com/api/1/route?point=51.131,12.414&point=48.224,3.867&vehicle=car&locale=en&calc_points=false&key={key}
![image](https://user-images.githubusercontent.com/7549325/82826899-cfe38700-9e62-11ea-8a21-47b69eb634f3.png)
![image](https://user-images.githubusercontent.com/7549325/82826911-d4a83b00-9e62-11ea-9a11-1e538e0a90d1.png)
@dpaulino suggested that the ".net httpclient collapses the 2 point params into one array", and according to the log, that's exactly what happened.
```
GET
https://graphhopper.com/api/1/route?
point=51.131%2c12.414%2c48.224%2c3.867&vehicle=car&locale=en&calc_points=false&key=b4138140-227f-4e99-8f72-ebe7904ac8a2
Sending request
```

**Comment by dpaulino** [comment]
Just reproduced the bug. Nightingale needs to not combine the two parameters into one. I will address this asap
