### ISSUE TITLE
Workspace Defaults

### ISSUE THREAD

**Issue by shaqaruden** [jenius-apps/nightingale-rest-api-client#75]
Every api request within my workspace has the accept and content-type headers set and has bearer authentication. Currently I need to set these for every request within my workspace. Would be nice if I could set those defaults on the workspace level.

**Comment by dpaulino** [comment]
Good feedback thanks. With regards to auth, if you have requests inside a collection, the requests can inherit the auth of the collection. So you can set the collection to have bearer auth, and all direct children requests can inherit that bearer auth. Not sure if this works for your situation, but I wanted to mention it just in case. 

I like workspace default suggestions though, thanks for that.

**Comment by shaqaruden** [comment]
wow how did I miss that. Thanks
