### ISSUE TITLE
Feature Request: F2 shortcut in Rename function

### ISSUE THREAD

**Issue by pinholucas** [jenius-apps/nightingale-rest-api-client#78]
It would be nice if you guys add this functionality. Also, I think that the border when the user are navigating in the Items list with arrow keys is too thick.

**Comment by dpaulino** [comment]
Just tried to implement this but the UX was subpar. Needs the changes that are coming Nightingale 4.0. I'll revisit this once Nightingale 4.0 is stable. Sorry for the delay

**Comment by pinholucas** [comment]
@dpaulino maybe it's about time? ahahah
