### ISSUE TITLE
Use environment variables to affect URL structure

### ISSUE THREAD

**Issue by drub0y** [jenius-apps/nightingale-rest-api-client#8]
My REST API returns the URL of a newly created resource via the `Location` header which I can extract into an environment variable using the "Chains" feature, however it seems that you can only use environment variables inside the body and maybe even query values, but I can't just use it as part of the URL.

Here's the scenario I'm looking to achieve:

As a result of a `POST` in `Request A`, the service returns the header `Location: http://localhost:1234/whatever/id123`. I set up a `Chain` as part of `Request A` to extract `request.Headers["Location"]` into a variable named `CurrentWhateverUrl`. I then want to be able to define a `Request B` whose URL is simply `{{CurrentWhateverUrl}}`, but that leads to the following error: `"Invalid URI: The hostname could not be parsed."`

**Comment by dpaulino** [comment]
@drub0y thank you for alerting me of this bug. Environment variables should be working for URL, so it seems there's a regression here. I will investigate this asap.

**Comment by dpaulino** [comment]
@drub0y After sending the `POST` to `Request A`, what value do you see in the "Manage Environment" view for the variable named `CurrentWhateverUrl`? Is the variable's value populated with the correct url string?

**Comment by dpaulino** [comment]
Hey @drub0y, just wanted to check in again. I tried reproducing this error, but things seemed to work fine for me. I was able to use a variable in the URL text field and I was able to update that using a chain. Let me know your thoughts on my previous comment:

> @drub0y After sending the POST to Request A, what value do you see in the "Manage Environment" view for the variable named CurrentWhateverUrl? Is the variable's value populated with the correct url string?

**Comment by dpaulino** [comment]
I've been able to get reproduction steps for a similar bug to what you described, though I'm not 100% sure if the situations are the same. I have implemented a fix and it will be rolling to production soon. Thanks for reporting this!
