### ISSUE TITLE
Crash on 'User-Agent' header when value ends with slash '/'

### ISSUE THREAD

**Issue by yuwono95** [jenius-apps/nightingale-rest-api-client#80]
![error](https://user-images.githubusercontent.com/11877181/86088543-c340f700-bad0-11ea-8387-fac57c47efa8.png)

**Comment by dpaulino** [comment]
Thanks for reporting this. I will look into it asap

**Comment by dpaulino** [comment]
hey @yuwono95, just wanted to double check: are you saying that you want to use `Shipper/` as your user agent? Because I think `Shipper/` may in fact be an invalid user agent

**Comment by yuwono95** [comment]
Yes, I need to implement API from https://shipper.id . It is required. I've tried it with another REST client (postman) and its working.

**Comment by dpaulino** [comment]
Turns out this was a bug in Nightingale. Big thanks @yuwono95 for reporting this issue. The fix will be coming in the next release.

**Comment by yuwono95** [comment]
OK, glad to hear that. Thanks.
