### ISSUE TITLE
“All files” in file picker is not truly all files

### ISSUE THREAD

**Issue by BreeceW** [jenius-apps/nightingale-rest-api-client#81]
In the file picker for form uploads, there is a long list of extensions listed as “All files.” It would be tremendously useful if it showed every file instead of just those listed, as in `filePicker.FileTypeFilter.Add("*");` were selectable.

**Comment by dpaulino** [comment]
Let me look into this. Our of curiosity, was there a specific file type you're looking to add that wasn't available?

**Comment by BreeceW** [comment]
> Let me look into this. Out of curiosity, was there a specific file type you're looking to use that wasn't available?

I was trying .appx at the time.

**Comment by dpaulino** [comment]
I changed this to allow all file types. Thanks for reporting the issue. This change will be available in the next update
