### ISSUE TITLE
Bungie.net OAuth Leads to "Cannot Connect to Service Error"

### ISSUE THREAD

**Issue by berwyn** [jenius-apps/nightingale-rest-api-client#83]
When attempting to use the built-in OAuth 2.0 feature, using OAuth for Bungie.net fails, leading to an error window (see attached). One thing I have noticed is that the window briefly flashes with the login flow, before showing this error, which I thought was particularly interesting!

![image](https://user-images.githubusercontent.com/1403744/86586382-cd8e4580-bf55-11ea-9cfe-b0da3f10d32c.png)

**Comment by dpaulino** [comment]
Thanks for reporting this issue, I'll look into this soon!

**Comment by dpaulino** [comment]
@berwyn dumb question but can you send a link for bungie's APIs? I'd like to reproduce this issue myself

**Comment by berwyn** [comment]
The page that'd probably be most helpful is their [OAuth documentation](https://github.com/Bungie-net/api/wiki/OAuth-Documentation), but the overall docs are [here](https://bungie-net.github.io/multi/index.html)

**Comment by dpaulino** [comment]
@berwyn sorry for the delayed follow up.

I was able to get the sign in window to show properly.
![image](https://user-images.githubusercontent.com/7649589/99153181-d60d3000-265b-11eb-8f14-7033699bb281.png)


And I was able to get an OAuth access token. Here's my configuration
![image](https://user-images.githubusercontent.com/7649589/99153407-36e93800-265d-11eb-9aa1-0185bf45d3ef.png)




Can you check if you're still seeing issues?

**Comment by dpaulino** [comment]
Closing as no repro in latest version. Feel free to reopen if you're still encountering an issue
