### ISSUE TITLE
Feature Request: Inherit parameters downwards

### ISSUE THREAD

**Issue by einkunz** [jenius-apps/nightingale-rest-api-client#86]
It would be nice if it was possible to add an parameter (Query, Header, Path) to a collection and inherit it downwards. (Like in the Window Store App "Project Rest")

**For example:**
I have a collection with 10 calls. Now i want to add an header parameter to all calls.
It would be nice if I can add it to the collection and inherit it downwards
For that, there can be 3 Buttons next to every parameter (or one button that opens a dialog with three buttons):
- Overwrite: Overwrites the parameter value in the calls if it exists
- Add: Adds the parameter with value to the calls if it does not exist
- Add and Overwrite: Adds the parameter with value to the calls if it does not exist or overwrites the value if it exists

**Comment by dpaulino** [comment]
I added queries and headers to collections. These values will be inherited by request children. Looking forward to your feedback on this once it releases over the next few days
![image](https://user-images.githubusercontent.com/7649589/87758735-ddadec80-c7c1-11ea-88e4-2bd8d1b137f4.png)
