### ISSUE TITLE
HttpClient error when sending any request

### ISSUE THREAD

**Issue by shaqaruden** [jenius-apps/nightingale-rest-api-client#87]
With a fresh install I am getting this error. All I have done is created a Workspace and a collection
![image](https://user-images.githubusercontent.com/5414897/87188026-1d556f80-c2bc-11ea-9a84-6f7b97858af6.png)

**Comment by dpaulino** [comment]
@shaqaruden did you close this accidentally?

**Comment by shaqaruden** [comment]
no this was the solution 

https://github.com/jenius-apps/nightingale-rest-api-client/blob/master/docs/localhost.md

**Comment by dpaulino** [comment]
Sorry about that. I have a task to improve the error messages. Glad you found the solution.
