### ISSUE TITLE
Add native support for Windows on ARM.

### ISSUE THREAD

**Issue by tboggs13** [jenius-apps/nightingale-rest-api-client#99]
The product already works well on Surface ProX in x32 mode, but would like to see the enhanced performance of full ARM64 native compatibility.

**Comment by dpaulino** [comment]
Hit a snag with this. adding arm64 doubles the build time, so my CI builds are failing due to the time limit. Pausing work on this for now as I try to investigate options around the build timeouts.

**Comment by dpaulino** [comment]
Tried some more work on this, and I'm hitting a snag on my CI pipeline. 
```
##[error]C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): Error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\ARM64\ilc\Tools64\nutc_driver.exe @"D:\a\1\s\Nightingale\obj\ARM64\Release\ilc\intermediate\MDIL\Nightingale.rsp"' returned exit code 2
```

Some searches online suggest this is due to running out of memory

**Comment by dpaulino** [comment]
Looks like the low memory theory may be correct. I was able to create an arm64 build locally where I have 16gb ram, while the CI pipeline only has 7gb. Also, I noticed that compiling for arm64 used up 6-7gb on my machine. This high memory usage may have led to the error in the CI pipeline.

**Comment by dpaulino** [comment]
ARM64 now available!

Download from store: https://www.microsoft.com/store/productId/9N2T6F9F5ZDN
Download from github: https://github.com/jenius-apps/nightingale-rest-api-client/releases/tag/v4.3.0

![image](https://user-images.githubusercontent.com/7649589/98005639-22c45180-1da6-11eb-9418-ed41e5a11077.png)
